package com.uabc.graficacionordenamientos;

import java.awt.Image;
import java.io.BufferedWriter;
import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.Random;
import javax.swing.Icon;
import javax.swing.ImageIcon;
import javax.swing.JLabel;
import java.util.Arrays;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
/**
 *
 * @author JesusOmar Leal
 */
public class Ventana extends javax.swing.JFrame {

    private ImageIcon imagen;
    private Icon icono;
    private boolean arreglosGenerados = false;
    private boolean archivo = false;
    private int arreglo1[] = new int[100];
    private int arreglo2[] = new int[500];
    private int arreglo3[] = new int[1000];
    private int arreglo4[] = new int[1500];
    private int arreglo5[] = new int[2000];
    private int arreglo6[] = new int[3000];
    private int arreglo7[] = new int[4000];
    private int arreglo8[] = new int[5000];
    private int arreglo9[] = new int[7000];
    private int arreglo10[] = new int[10000];

    public Ventana() {

        initComponents();
        this.setLocationRelativeTo(this);
        this.setBackground(Background, "C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\GraficacionOrdenamientos\\src\\main\\java\\com\\uabc\\graficacionordenamientos\\assets\\fondo.jpg");
    }

    private void setBackground(JLabel lbl, String url) {

        this.imagen = new ImageIcon(url);

        this.icono = new ImageIcon(this.imagen.getImage().getScaledInstance(lbl.getWidth(), lbl.getHeight(), Image.SCALE_DEFAULT));

        lbl.setIcon(this.icono);

        this.repaint();
    }

    /**
     * This method is called from within the constructor to initialize the form. WARNING: Do NOT modify this code. The content of this method is always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        generarBoton = new javax.swing.JToggleButton();
        OrdenarBoton = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        Titulo = new javax.swing.JLabel();
        Background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        generarBoton.setText("Generar Arreglos");
        generarBoton.setContentAreaFilled(false);
        generarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(generarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 120, 180, -1));

        OrdenarBoton.setText("Ordenar");
        OrdenarBoton.setContentAreaFilled(false);
        OrdenarBoton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                OrdenarBotonActionPerformed(evt);
            }
        });
        jPanel1.add(OrdenarBoton, new org.netbeans.lib.awtextra.AbsoluteConstraints(150, 270, 180, -1));

        jLabel1.setText("Mostrar Graficas");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 90, -1, -1));

        jCheckBox1.setText("QuickSort();");
        jCheckBox1.setContentAreaFilled(false);
        jPanel1.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 120, -1, -1));

        jCheckBox2.setText("MergeSort();");
        jCheckBox2.setContentAreaFilled(false);
        jPanel1.add(jCheckBox2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 170, -1, -1));

        jCheckBox3.setText("Sort();");
        jCheckBox3.setContentAreaFilled(false);
        jPanel1.add(jCheckBox3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 220, -1, -1));

        jCheckBox4.setText("ParallelSort();");
        jCheckBox4.setContentAreaFilled(false);
        jPanel1.add(jCheckBox4, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 270, -1, -1));

        Titulo.setIcon(new javax.swing.ImageIcon("C:\\Users\\omar-\\OneDrive\\Documentos\\NetBeansProjects\\GraficacionOrdenamientos\\src\\main\\java\\com\\uabc\\graficacionordenamientos\\assets\\titulo.png")); // NOI18N
        jPanel1.add(Titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 10, -1, -1));
        jPanel1.add(Background, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 350, 310));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void generarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generarBotonActionPerformed

        rellenarAleatorio(arreglo1);
        rellenarAleatorio(arreglo2);
        rellenarAleatorio(arreglo3);
        rellenarAleatorio(arreglo4);
        rellenarAleatorio(arreglo5);
        rellenarAleatorio(arreglo6);
        rellenarAleatorio(arreglo7);
        rellenarAleatorio(arreglo8);
        rellenarAleatorio(arreglo9);
        rellenarAleatorio(arreglo10);

        this.arreglosGenerados = true;
        JOptionPane.showMessageDialog(this, "Arreglos Generados Con Exito", "Aviso", JOptionPane.INFORMATION_MESSAGE);
    }//GEN-LAST:event_generarBotonActionPerformed

    private void OrdenarBotonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OrdenarBotonActionPerformed
        if (arreglosGenerados) {

            resetCSV();

            casoUno(arreglo1, 1);
            casoDos(arreglo1, 1);
            ordenarMayorMenor(arreglo1);
            casoTres(arreglo1, 1);

            casoUno(arreglo2, 2);
            casoDos(arreglo2, 2);
            ordenarMayorMenor(arreglo2);
            casoTres(arreglo2, 2);

            casoUno(arreglo3, 3);
            casoDos(arreglo3, 3);
            ordenarMayorMenor(arreglo3);
            casoTres(arreglo3, 3);

            casoUno(arreglo4, 4);
            casoDos(arreglo4, 4);
            ordenarMayorMenor(arreglo4);
            casoTres(arreglo4, 4);

            casoUno(arreglo5, 5);
            casoDos(arreglo5, 5);
            ordenarMayorMenor(arreglo5);
            casoTres(arreglo5, 5);

            casoUno(arreglo6, 6);
            casoDos(arreglo6, 6);
            ordenarMayorMenor(arreglo6);
            casoTres(arreglo6, 6);

            casoUno(arreglo7, 7);
            casoDos(arreglo7, 7);
            ordenarMayorMenor(arreglo7);
            casoTres(arreglo7, 7);

            casoUno(arreglo8, 8);
            casoDos(arreglo8, 8);
            ordenarMayorMenor(arreglo8);
            casoTres(arreglo8, 8);

            casoUno(arreglo9, 9);
            casoDos(arreglo9, 9);
            ordenarMayorMenor(arreglo9);
            casoTres(arreglo9, 9);

            casoUno(arreglo10, 10);
            casoDos(arreglo10, 10);
            ordenarMayorMenor(arreglo10);
            casoTres(arreglo10, 10);

        } else {
            JOptionPane.showMessageDialog(this, "No Se Han Generado Los Arreglos", "Error", JOptionPane.INFORMATION_MESSAGE);
        }

    }//GEN-LAST:event_OrdenarBotonActionPerformed

    public void casoUno(int[] arreglo, int numArreglo) {

        System.out.println("Caso 1 Arreglo Desordenado:");

        int[] copiaArreglo = generarCopia(arreglo);

        System.out.println("Merge Sort:");
        ordenarMergeSort(copiaArreglo, numArreglo, 1);

        System.out.println("Quick Sort:");
        copiaArreglo = generarCopia(arreglo);
        ordenarQuickSort(copiaArreglo, numArreglo, 1);

        System.out.println("Sort:");
        copiaArreglo = generarCopia(arreglo);
        ordenarSort(copiaArreglo, numArreglo, 1);

        System.out.println("ParallelSort:");
        copiaArreglo = generarCopia(arreglo);
        ordenarParallelSort(copiaArreglo, numArreglo, 1);

    }

    public void casoDos(int[] arreglo, int numArreglo) {
        System.out.println("Caso 2 Arreglo Ya Ordenado:");
        System.out.println("Merge Sort:");
        ordenarMergeSort(arreglo, numArreglo, 2);
        System.out.println("Quick Sort:");
        ordenarQuickSort(arreglo, numArreglo, 2);
        System.out.println("Sort:");
        ordenarSort(arreglo, numArreglo, 2);
        System.out.println("ParallelSort:");
        ordenarParallelSort(arreglo, numArreglo, 2);
    }

    public void casoTres(int[] arreglo, int numArreglo) {
        System.out.println("Caso 3 Orden Decedente:");

        int[] copiaArreglo = generarCopia(arreglo);

        System.out.println("Merge Sort:");
        ordenarMergeSort(copiaArreglo, numArreglo, 3);

        System.out.println("Quick Sort:");
        copiaArreglo = generarCopia(arreglo);
        ordenarQuickSort(copiaArreglo, numArreglo, 3);

        System.out.println("Sort:");
        copiaArreglo = generarCopia(arreglo);
        ordenarSort(copiaArreglo, numArreglo, 3);

        System.out.println("ParallelSort:");
        copiaArreglo = generarCopia(arreglo);
        ordenarParallelSort(copiaArreglo, numArreglo, 3);
    }

    public void ordenarMayorMenor(int[] arreglo) {
        int n = arreglo.length;

        for (int i = 0; i < n - 1; i++) {
            for (int j = 0; j < n - i - 1; j++) {
                if (arreglo[j] < arreglo[j + 1]) {

                    int temp = arreglo[j];
                    arreglo[j] = arreglo[j + 1];
                    arreglo[j + 1] = temp;
                }
            }
        }
        //mostrarArreglo(arreglo);
    }

    public void ordenarMergeSort(int[] arreglo, int numArreglo, int caso) {

        int dimension = arreglo.length;

        long starTime = System.nanoTime();

        mergeSort(arreglo);

        long endTime = System.nanoTime();

        long tiempoEjecucion = endTime - starTime;

        System.out.println("Tiempo de Ejecucion es:" + tiempoEjecucion + " nanosegundos");

        escribirCSV("mergeSort(caso" + caso + ").csv", numArreglo, dimension, tiempoEjecucion);

    }

    public void ordenarQuickSort(int[] arreglo, int numArreglo, int caso) {

        int dimension = arreglo.length;

        int n = arreglo.length;

        long starTime = System.nanoTime();

        quickSort(arreglo, 0, n - 1);

        long endTime = System.nanoTime();

        long tiempoEjecucion = endTime - starTime;

        System.out.println("Tiempo de Ejecucion es:" + tiempoEjecucion + " nanosegundos");

        escribirCSV("QuickSort(caso" + caso + ").csv", numArreglo, dimension, tiempoEjecucion);
    }

    public void ordenarSort(int[] arreglo, int numArreglo, int caso) {

        int dimension = arreglo.length;

        long starTime = System.nanoTime();

        Arrays.sort(arreglo);

        long endTime = System.nanoTime();

        long tiempoEjecucion = endTime - starTime;

        System.out.println("Tiempo de Ejecucion es:" + tiempoEjecucion + " nanosegundos");

        escribirCSV("Sort(caso" + caso + ").csv", numArreglo, dimension, tiempoEjecucion);
    }

    public void ordenarParallelSort(int[] arreglo, int numArreglo, int caso) {

        int dimension = arreglo.length;

        long starTime = System.nanoTime();

        Arrays.parallelSort(arreglo);

        long endTime = System.nanoTime();

        long tiempoEjecucion = endTime - starTime;

        System.out.println("Tiempo de Ejecucion es:" + tiempoEjecucion + " nanosegundos");

        escribirCSV("ParallelSort(caso" + caso + ").csv", numArreglo, dimension, tiempoEjecucion);
    }

    public void mostrarArreglo(int[] arreglo) {

        for (int i = 0; i < arreglo.length; i++) {
            System.out.println("" + arreglo[i]);
        }

    }

    public void rellenarAleatorio(int[] arreglo) {

        Random numeroAleatorio = new Random();

        for (int i = 0; i < arreglo.length; i++) {

            arreglo[i] = numeroAleatorio.nextInt();

        }

    }

    public int[] generarCopia(int[] arreglo) {

        int arregloCopia[] = new int[arreglo.length];

        System.arraycopy(arreglo, 0, arregloCopia, 0, arreglo.length);

        return arregloCopia;
    }

    static void intercambiar(int[] arr, int i, int j) {
        int temp = arr[i];
        arr[i] = arr[j];
        arr[j] = temp;
    }

    static int particion(int[] arr, int low, int high) {

        int pivot = arr[high];

        int i = (low - 1);

        for (int j = low; j <= high - 1; j++) {

            if (arr[j] < pivot) {

                i++;
                intercambiar(arr, i, j);
            }
        }
        intercambiar(arr, i + 1, high);
        return (i + 1);
    }

    static void quickSort(int[] arr, int low, int high) {
        if (low < high) {

            int pi = particion(arr, low, high);

            quickSort(arr, low, pi - 1);
            quickSort(arr, pi + 1, high);
        }
    }

    static void mergeSort(int[] Arreglo) {
        int longitudArreglo = Arreglo.length;

        if (longitudArreglo < 2) {
            return;
        }

        int mitadArreglo = longitudArreglo / 2;
        int[] mitadIzquierda = new int[mitadArreglo];
        int[] mitadDerecha = new int[longitudArreglo - mitadArreglo];

        for (int i = 0; i < mitadArreglo; i++) {
            mitadIzquierda[i] = Arreglo[i];
        }
        for (int i = mitadArreglo; i < longitudArreglo; i++) {
            mitadDerecha[i - mitadArreglo] = Arreglo[i];
        }

        mergeSort(mitadIzquierda);
        mergeSort(mitadDerecha);

        merge(Arreglo, mitadIzquierda, mitadDerecha);
    }

    static void merge(int[] Arreglo, int[] mitadIzquierda, int[] mitadDerecha) {

        int mitadIzquierda_tamano = mitadIzquierda.length;
        int mitadDerecha_tamano = mitadDerecha.length;

        int indiceIzquierdo = 0, indiceDerecho = 0, indiceFinal = 0;

        while (indiceIzquierdo < mitadIzquierda_tamano && indiceDerecho < mitadDerecha_tamano) {
            if (mitadIzquierda[indiceIzquierdo] <= mitadDerecha[indiceDerecho]) {
                Arreglo[indiceFinal] = mitadIzquierda[indiceIzquierdo];
                indiceIzquierdo++;
            } else {
                Arreglo[indiceFinal] = mitadDerecha[indiceDerecho];
                indiceDerecho++;
            }
            indiceFinal++;
        }

        while (indiceIzquierdo < mitadIzquierda_tamano) {
            Arreglo[indiceFinal] = mitadIzquierda[indiceIzquierdo];
            indiceIzquierdo++;
            indiceFinal++;
        }

        while (indiceDerecho < mitadDerecha_tamano) {
            Arreglo[indiceFinal] = mitadDerecha[indiceDerecho];
            indiceDerecho++;
            indiceFinal++;
        }

    }

    private void resetCSV() {
        borrarContenidoCSV("mergeSort(caso1).csv");
        borrarContenidoCSV("mergeSort(caso2).csv");
        borrarContenidoCSV("mergeSort(caso3).csv");
        borrarContenidoCSV("Sort(caso1).csv");
        borrarContenidoCSV("Sort(caso2).csv");
        borrarContenidoCSV("Sort(caso3).csv");
        borrarContenidoCSV("QuickSort(caso1).csv");
        borrarContenidoCSV("QuickSort(caso2).csv");
        borrarContenidoCSV("QuickSort(caso3).csv");
        borrarContenidoCSV("ParallelSort(caso1).csv");
        borrarContenidoCSV("ParallelSort(caso2).csv");
        borrarContenidoCSV("ParallelSort(caso3).csv");
    }

    private void borrarContenidoCSV(String nombreArchivo) {

        try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo, false))) {

        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error al escribir en el archivo: " + e.getMessage());
        }

    }

    private void escribirCSV(String nombreArchivo, int noCorrida, int dimensionArreglo, long tiempo) {
        try (BufferedWriter writer = new BufferedWriter(new FileWriter(nombreArchivo, true))) {
            File file = new File(nombreArchivo);
            if (file.length() == 0) {
                writer.write("noCorrida,dimensionArreglo,tiempo");
                writer.newLine();

            }
            String linea = noCorrida + "," + dimensionArreglo + "," + tiempo;
            writer.write(linea);
            writer.newLine();
        } catch (IOException e) {
            e.printStackTrace();
            System.err.println("Error al escribir en el archivo: " + e.getMessage());
        }

    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ventana.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ventana().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Background;
    private javax.swing.JToggleButton OrdenarBoton;
    private javax.swing.JLabel Titulo;
    private javax.swing.JToggleButton generarBoton;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    // End of variables declaration//GEN-END:variables

}
